SUBROUTINE SPCM_SIMPLE (YDGEOMETRY,YDMODEL,PSPSP,PSPVOR,PSPDIV,PSPT,PSPSPD,PSPSVD)

USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)      ,INTENT(IN)    :: YDGEOMETRY
TYPE(MODEL)         ,INTENT(INOUT) :: YDMODEL
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPSP (YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPVOR(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPDIV(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPT  (YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPSPD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPSVD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)

#include "spcsi.intfb.h"
#include "trmtos.intfb.h"
#include "trstom.intfb.h"

INTEGER(KIND=JPIM) :: IM, IMLOC, ISPEC2V

#if defined(_OPENACC)
REAL(KIND=JPRB)  ::zsdiv(1:YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  ::zhelp(1:YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  ::zst(1:YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  ::zsp(1:YDGEOMETRY%YRMP%NSPEC2V)
REAL(KIND=JPRB)  ::zsdivp(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  ::zspdivp(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  ::zsphi(YDGEOMETRY%YRMP%NSPEC2V,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB)  ::zout(YDGEOMETRY%YRMP%NSPEC2V,0:YDGEOMETRY%YRDIMV%NFLEVG)
#endif


REAL(KIND=JPRB), ALLOCATABLE :: ZSPVORG2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPDIVG2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTG2  (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSPDG2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSVDG2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSPG2 (:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTNDSI_VORG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTNDSI_DIVG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTNDSI_TG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPVORG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPDIVG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTG  (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSPDG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSVDG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSPG (:)

REAL(KIND=JPHOOK) ::  ZHOOK_HANDLE,zhook_handle2
INTEGER(KIND=JPIM) ::compteur1,compteur2

IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE',0,ZHOOK_HANDLE)

ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,  YDMP=>YDGEOMETRY%YRMP, YDDYN=>YDMODEL%YRML_DYN%YRDYN,   &
&  YDDYNA=>YDMODEL%YRML_DYN%YRDYNA, YDLDDH=>YDMODEL%YRML_DIAG%YRLDDH, YDSPDDH=>YDMODEL%YRML_DIAG%YRSPDDH)

ASSOCIATE(NFLEVG=>YDDIMV%NFLEVG, NSPEC2V=>YDMP%NSPEC2V, NSPEC2VF=>YDMP%NSPEC2VF)

ISPEC2V=MAX(NSPEC2V,NSPEC2VF)

ALLOCATE(ZSPVORG2(NFLEVG,ISPEC2V))
ALLOCATE(ZSPDIVG2(NFLEVG,ISPEC2V))
ALLOCATE(ZSPTG2  (NFLEVG,ISPEC2V))
ALLOCATE(ZSPSPDG2(NFLEVG,ISPEC2V))
ALLOCATE(ZSPSVDG2(NFLEVG,ISPEC2V))
ALLOCATE(ZSPSPG2 (ISPEC2V))

#if defined(_OPENACC)
ALLOCATE(ZSPVORG(ISPEC2V,nflevg))
ALLOCATE(ZSPDIVG(ISPEC2V,nflevg))
ALLOCATE(ZSPTG  (ISPEC2V,nflevg))
ALLOCATE(ZSPSPDG(ISPEC2V,nflevg))
ALLOCATE(ZSPSVDG(ISPEC2V,nflevg))
ALLOCATE(ZSPSPG (ISPEC2V))
#else
ALLOCATE(ZSPVORG(NFLEVG,ISPEC2V))
ALLOCATE(ZSPDIVG(NFLEVG,ISPEC2V))
ALLOCATE(ZSPTG  (NFLEVG,ISPEC2V))
ALLOCATE(ZSPSPDG(NFLEVG,ISPEC2V))
ALLOCATE(ZSPSVDG(NFLEVG,ISPEC2V))
ALLOCATE(ZSPSPG (ISPEC2V))
#endif

ALLOCATE(ZSPTNDSI_VORG(1,1))
ALLOCATE(ZSPTNDSI_DIVG(1,1))
ALLOCATE(ZSPTNDSI_TG(1,1))
  
CALL TRMTOS(YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,&
  & PSPVOR=PSPVOR,PSPDIV=PSPDIV,PSPT=PSPT,PSPSPD=PSPSPD,&
  & PSPSVD=PSPSVD,PSPSP=PSPSP,&
  & PSPVORG=ZSPVORG2,PSPDIVG=ZSPDIVG2,PSPTG=ZSPTG2,PSPSPDG=ZSPSPDG2,&
  & PSPSVDG=ZSPSVDG2,PSPSPG=ZSPSPG2,&
  & LDFULLM=.FALSE.)

IF (NSPEC2V > 0) THEN
  IM=-999
  IMLOC=-999

IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transpose1',0,ZHOOK_HANDLE2)
#if defined(_OPENACC)
zspspg(:)=zspspg2(:)
do compteur1=1,nflevg
  do compteur2=1,ispec2V
    zspvorg(compteur1,compteur2)=zspvorg2(compteur2,compteur1)
    zspdivg(compteur1,compteur2)=zspdivg2(compteur2,compteur1)
    zsptg(compteur1,compteur2)=zsptg2(compteur2,compteur1)
    zspspdg(compteur1,compteur2)=zspspdg2(compteur2,compteur1)
    zspsvdg(compteur1,compteur2)=zspsvdg2(compteur2,compteur1)
  end do
end do
#else
zspspg(:)=zspspg2(:)
zspvorg(:,:)=zspvorg2(:,:)
zspdivg(:,:)=zspdivg2(:,:)
zsptg(:,:)=zsptg2(:,:)
zspspdg(:,:)=zspspdg2(:,:)
zspsvdg(:,:)=zspsvdg2(:,:)
#endif
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transpose1',1,ZHOOK_HANDLE2)


#if defined(_OPENACC)
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transfert1a',0,ZHOOK_HANDLE2)
!$acc data copy(zspdivg,zsptg,zspspg)
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transfert1a',1,ZHOOK_HANDLE2)
#endif

#if defined(_OPENACC)
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transfert1b',0,ZHOOK_HANDLE2)
!$acc data create(zsdiv,zhelp,zsp,zst,zsphi,zout,zsdivp,zspdivp)
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transfert1b',1,ZHOOK_HANDLE2)
  CALL SPCSI(YDGEOMETRY, YDMODEL%YRCST, YDLDDH, YDMODEL%YRML_GCONF%YRRIP, YDDYN, IM, IMLOC, 1, &
  & NSPEC2V, .FALSE.,  ZSPVORG, ZSPDIVG, ZSPTG, ZSPSPG, ZSPTNDSI_VORG, ZSPTNDSI_DIVG, ZSPTNDSI_TG,zsdiv,zhelp,zsp,zst,zsdivp,zspdivp,zsphi,zout)
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transfert2b',0,ZHOOK_HANDLE2)
!$acc end data
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transfert2a',1,ZHOOK_HANDLE2)
#else
  CALL SPCSI(YDGEOMETRY, YDMODEL%YRCST, YDLDDH, YDMODEL%YRML_GCONF%YRRIP, YDDYN, IM, IMLOC, 1, &
  & NSPEC2V, .FALSE.,  ZSPVORG, ZSPDIVG, ZSPTG, ZSPSPG, ZSPTNDSI_VORG, ZSPTNDSI_DIVG, ZSPTNDSI_TG)
#endif

#if defined(_OPENACC)
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transfert2a',0,ZHOOK_HANDLE2)
!$acc end data
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transfert2a',1,ZHOOK_HANDLE2)
#endif

IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transpose2',0,ZHOOK_HANDLE2)
#if defined(_OPENACC)
zspspg2(:)=zspspg(:)
do compteur1=1,ispec2v
  do compteur2=1,nflevg
    zspvorg2(compteur1,compteur2)=zspvorg(compteur2,compteur1)
    zspdivg2(compteur1,compteur2)=zspdivg(compteur2,compteur1)
    zsptg2(compteur1,compteur2)=zsptg(compteur2,compteur1)
    zspspdg2(compteur1,compteur2)=zspspdg(compteur2,compteur1)
    zspsvdg2(compteur1,compteur2)=zspsvdg(compteur2,compteur1)
  end do
end do
#else
zspspg2(:)=zspspg(:)
zspvorg2(:,:)=zspvorg(:,:)
zspdivg2(:,:)=zspdivg(:,:)
zsptg2(:,:)=zsptg(:,:)
zspspdg2(:,:)=zspspdg(:,:)
zspsvdg2(:,:)=zspsvdg(:,:)
#endif
IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE_transpose2',1,ZHOOK_HANDLE2)

ENDIF 

!     - Transpose spectral data back to level structure

CALL TRSTOM(&
   & YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,&
   & PSPVORG=ZSPVORG2,PSPDIVG=ZSPDIVG2,PSPTG=ZSPTG2,PSPSPDG=ZSPSPDG2,&
   & PSPSVDG=ZSPSVDG2,PSPSPG=ZSPSPG2,&
   & PSPVOR=PSPVOR,PSPDIV=PSPDIV,PSPT=PSPT,PSPSPD=PSPSPD,&
   & PSPSVD=PSPSVD,PSPSP=PSPSP,&
   & LDFULLM=.FALSE.,LDNEEDPS=.TRUE.)  

IF (ALLOCATED(ZSPVORG)) DEALLOCATE(ZSPVORG)
IF (ALLOCATED(ZSPDIVG)) DEALLOCATE(ZSPDIVG)
IF (ALLOCATED(ZSPTG))   DEALLOCATE(ZSPTG)
IF (ALLOCATED(ZSPSPDG)) DEALLOCATE(ZSPSPDG)
IF (ALLOCATED(ZSPSVDG)) DEALLOCATE(ZSPSVDG)
IF (ALLOCATED(ZSPSPG))  DEALLOCATE(ZSPSPG)

IF (ALLOCATED(ZSPVORG2)) DEALLOCATE(ZSPVORG2)
IF (ALLOCATED(ZSPDIVG2)) DEALLOCATE(ZSPDIVG2)
IF (ALLOCATED(ZSPTG2))   DEALLOCATE(ZSPTG2)
IF (ALLOCATED(ZSPSPDG2)) DEALLOCATE(ZSPSPDG2)
IF (ALLOCATED(ZSPSVDG2)) DEALLOCATE(ZSPSVDG2)
IF (ALLOCATED(ZSPSPG2))  DEALLOCATE(ZSPSPG2)


IF (ALLOCATED(ZSPTNDSI_VORG)) DEALLOCATE(ZSPTNDSI_VORG)
IF (ALLOCATED(ZSPTNDSI_DIVG)) DEALLOCATE(ZSPTNDSI_DIVG)
IF (ALLOCATED(ZSPTNDSI_TG))   DEALLOCATE(ZSPTNDSI_TG)

END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE',1,ZHOOK_HANDLE)

END SUBROUTINE SPCM_SIMPLE

